; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-arduino

[flags:runtime]
build_flags =
	-Wall
	-Wextra

[common]
build_flags =
	-std=gnu++11

[common:arduino]
extends = common
lib_deps =
;	SPI
;	Wire
build_flags =
	${common.build_flags}
	-DUSE_ARDUINO

[common:esp32-arduino]
extends = common:arduino
platform = espressif32
framework = arduino
lib_deps =
    ${common:arduino.lib_deps}
;	FS
	WiFi
	PubSubClient
build_flags =
	${common:arduino.build_flags}
	-DUSE_ESP32
	-DUSE_ESP32_FRAMEWORK_ARDUINO
	!if [ -n "$WIFI_SSID" ]; then echo "-DWIFI_SSID=\\\"$WIFI_SSID\\\""; fi
	!if [ -n "$WIFI_PASSWORD" ]; then echo "-DWIFI_PASSWORD=\\\"$WIFI_PASSWORD\\\""; fi

[env:esp32-arduino]
extends = common:esp32-arduino
board = esp32dev
build_flags =
    ${common:esp32-arduino.build_flags}
    ${flags:runtime.build_flags}

[env:esp32-s3-arduino]
extends = common:esp32-arduino
board = esp32-s3-devkitc-1
build_flags =
    ${common:esp32-arduino.build_flags}
    ${flags:runtime.build_flags}

;[common:idf]
;extends = common
;build_flags =
;	${common.build_flags}
;	-DUSE_ESP_IDF
;lib_deps =
;
;[common:esp32-idf]
;extends = common:idf
;platform = espressif32
;framework = espidf
;build_flags =
;	${common:idf.build_flags}
;	-DUSE_ESP32
;	-DUSE_ESP32_FRAMEWORK_ESP_IDF
;
;[env:esp32-idf]
;extends = common:esp32-idf
;board = esp32dev
;build_flags =
;	${common:esp32-idf.build_flags}
;	${flags:runtime.build_flags}
;check_tool = cppcheck
;check_flags =
;	cppcheck: --enable=all
;check_skip_packages = yes
;
;[env:esp32-s3-idf]
;extends = common:esp32-idf
;board = esp32-s3-devkitc-1
;build_flags =
;	${common:esp32-idf.build_flags}
;	${flags:runtime.build_flags}
;	-DUSE_ESP32_VARIANT_ESP32S3
;check_tool = cppcheck
;check_flags =
;	cppcheck: --enable=all
;check_skip_packages = yes
