/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.4/samples
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.danilopianini.gradle-java-qa") version "1.178.0"
    id("com.gradleup.shadow") version "9.4.1"
    id("com.github.spotbugs") version "6.5.8" // https://spotbugs.readthedocs.io/en/latest/gradle.html
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // SpotBugs annotations
    //compileOnly("com.github.spotbugs:spotbugs-annotations:4.10.2")
    implementation("com.github.spotbugs:spotbugs-annotations:4.10.2")

    // This dependency is used by the application.
    implementation(libs.guava)
    // Library for serial port communication
    implementation("io.github.java-native:jssc:2.10.2")
    // Library for MQTT client
    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")
    // Library for Json parsing/building
    implementation("com.google.code.gson:gson:2.14.0")
    // Library for CLI parameters handling
    implementation("info.picocli:picocli:4.7.7")
    annotationProcessor("info.picocli:picocli-codegen:4.7.7")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.cus.CUS"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging { events("passed", "skipped", "failed") }
    testLogging.showStandardStreams = true
}

gradle.taskGraph.whenReady {
    if (allTasks.any { it.name == "check" }) {
        tasks.withType<JavaCompile>().configureEach {
            options.compilerArgs.add("-Xlint:unchecked")
        }
    }
}
