; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = arduino_uno

[flags:runtime]
build_flags =
    -Wall
    -Wextra

[common]
build_flags =
    -std=gnu++11

[common:arduino]
extends = common
lib_deps =
    SPI
    Wire
    marcoschwartz/LiquidCrystal_I2C@1.1.4
build_flags =
    ${common.build_flags}
    -DUSE_ARDUINO

[common:arduino_uno]
extends = common:arduino
platform = atmelavr
framework = arduino

[env:arduino_uno]
extends = common:arduino_uno
board = uno
check_tool = cppcheck
check_flags =
    cppcheck: --std=c++11 --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=unmatchedSuppression
check_skip_packages = yes
